In [ ]:
# 02-2 스크래핑 사용하기

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.jupyter.org/github/rickiepark/hg-da/blob/main/02-2.ipynb"><img src="https://jupyter.org/assets/share.png" width="61" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/hg-da/blob/main/02-2.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## 검색 결과 페이지 가져오기

In [37]:
import gdown

gdown.download('https://bit.ly/3q9SZix', '20s_best_book.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: C:\Users\YW\Desktop\mot\hg-da-main\20s_best_book.json
100%|█████████████████████████████████████████████████████████████████████████████| 92.9k/92.9k [00:00<00:00, 1.21MB/s]

'20s_best_book.json'

In [108]:
import pandas as pd

books_df = pd.read_json('20s_best_book.json')
books_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...

In [109]:
import requests

isbn = 9788954672214     
url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'

r = requests.get(url.format(isbn))

## 뷰티플수프

In [110]:
from bs4 import BeautifulSoup

In [111]:
soup = BeautifulSoup(r.text, 'html.parser')

In [112]:
prd_link = soup.find('a', attrs={'class':'gd_name'})

In [113]:
print(prd_link)

<a class="gd_name" href="/product/goods/90367403" onclick="wiseLogV2('S', '101_005_003_001', ''); setGoodsClickExtraCodeHub('032', '9788954672214', '90367403', '0',this);">시선으로부터,</a>

In [114]:
print(prd_link['href'])

/product/goods/90367403

In [115]:
url = 'http://www.yes24.com'+prd_link['href']
r = requests.get(url)

In [117]:
soup = BeautifulSoup(r.text, 'html.parser')
prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
print(prd_detail)

<div class="gd_infoSet infoSet_noLine" id="infoset_specific">
<div class="tm_infoSet">
<h4 class="tit_txt">품목정보</h4>
</div>
<div class="infoSetCont_wrap">
<div class="yesTb">
<table class="tb_nor tb_vertical" summary="품목정보 국내도서, 외국도서 " width="100%">
<caption>품목정보</caption>
<colgroup>
<col width="170"/>
<col width="*"/>
</colgroup>
<tbody class="b_size">
<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2020년 06월 05일</td>
</tr>
<tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">340쪽 | 412g | 133*200*23mm</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9788954672214</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">8954672213</td>
</tr>
</tbody>
</table>
</div>
</div>
<script type="text/javascript">
        if ($("#infoset_specific table tbody tr").length == 0) {
            $("#infoset_specific").remove();
        }
    </script>
</div>

In [118]:
prd_tr_list = prd_detail.find_all('tr')
print(prd_tr_list)

[<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2020년 06월 05일</td>
</tr>, <tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">340쪽 | 412g | 133*200*23mm</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9788954672214</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">8954672213</td>
</tr>]

In [119]:
for tr in prd_tr_list:
    if tr.find('th').get_text() == '쪽수, 무게, 크기':
        page_td = tr.find('td').get_text()
        
    elif tr.find('th').get_text() == '발행일':
        page_td2 = tr.find('td').get_text()

In [120]:
print(page_td)
print(page_td2)

340쪽 | 412g | 133*200*23mm
2020년 06월 05일

In [121]:
print(page_td.split()[0])
print(page_td2)

340쪽
2020년 06월 05일

## 전체 도서의 쪽수 구하기

In [122]:
def get_page_cnt(isbn):
    # Yes24 도서 검색 페이지 URL
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
    # URL에 ISBN을 넣어 HTML 가져옵니다.
    r = requests.get(url.format(isbn))
    soup = BeautifulSoup(r.text, 'html.parser')   # HTML 파싱
    # 검색 결과에서 해당 도서를 선택합니다.
    prd_info = soup.find('a', attrs={'class':'gd_name'})
    if prd_info == None:
        return ''
    # 도서 상세 페이지를 가져옵니다.
    url = 'http://www.yes24.com'+prd_info['href']
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    # 상품 상세정보 div를 선택합니다.
    prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
    # 테이블에 있는 tr 태그를 가져옵니다.
    prd_tr_list = prd_detail.find_all('tr')
    # 쪽수가 들어 있는 th를 찾아 td에 담긴 값을 반환합니다.
    for tr in prd_tr_list:
        if tr.find('th').get_text() == '쪽수, 무게, 크기':
            page = tr.find('td').get_text().split()[0]
            weight = tr.find('td').get_text().split()[2]
            size = tr.find('td').get_text().split()[4]
        if tr.find('th').get_text() == '발행일':
            date = tr.find('td').get_text().split()
    return page,weight,size,date

In [123]:
get_page_cnt(9791165341909)

('300쪽', '358g', '134*200*20mm', ['2020년', '07월', '08일'])

In [124]:
top10_books = books_df.head(10)

In [125]:
def get_page_cnt2(row):
    isbn = row['isbn13']
    return get_page_cnt(isbn)

In [126]:
page_count = top10_books.apply(get_page_cnt2, axis=1)
print(page_count)

0    (344쪽, 496g, 130*198*30mm, [2019년, 06월, 24일])
1    (300쪽, 358g, 134*200*20mm, [2020년, 07월, 08일])
2    (228쪽, 296g, 130*195*15mm, [2019년, 07월, 31일])
3    (340쪽, 412g, 133*200*23mm, [2020년, 06월, 05일])
4    (264쪽, 388g, 134*195*20mm, [2017년, 03월, 31일])
5    (396쪽, 512g, 145*210*30mm, [2016년, 11월, 21일])
6    (272쪽, 318g, 137*197*18mm, [2020년, 01월, 06일])
7
8    (244쪽, 324g, 140*210*16mm, [2019년, 07월, 17일])
9    (296쪽, 406g, 145*210*20mm, [2016년, 07월, 04일])
dtype: object

In [62]:
page_count = top10_books.apply(lambda row: get_page_cnt(row['isbn13']), axis=1)

In [80]:
page_count.name = 'page_count'
print(page_count[0][0])

344쪽

In [85]:
results = []
for isbn in top10_books['isbn13']:
    results.append(get_page_cnt(isbn))
    
page_count = pd.DataFrame(results, 
                          columns=['쪽수', '무게', '크기', '발행일'], 
                          index=top10_books.index)

In [86]:
top10_with_page_count = pd.merge(top10_books, page_count,
                                 left_index=True, right_index=True)
top10_with_page_count

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL,쪽수,무게,크기,발행일
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...,344쪽,496g,130*198*30mm,"[2019년, 06월, 24일]"
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...,300쪽,358g,134*200*20mm,"[2020년, 07월, 08일]"
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...,228쪽,296g,130*195*15mm,"[2019년, 07월, 31일]"
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...,340쪽,412g,133*200*23mm,"[2020년, 06월, 05일]"
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...,264쪽,388g,134*195*20mm,"[2017년, 03월, 31일]"
5,6,6,피프티 피플 :정세랑 장편소설,지은이: 정세랑,창비,2016,9788936434243,03810,,813.7,문학 > 한국문학 > 소설,320,https://bookthumb-phinf.pstatic.net/cover/113/...,396쪽,512g,145*210*30mm,"[2016년, 11월, 21일]"
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005,03810,,813.7,문학 > 한국문학 > 소설,319,https://image.aladin.co.kr/product/22246/11/co...,272쪽,318g,137*197*18mm,"[2020년, 01월, 06일]"
7,8,8,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9788972756194,03830,,833.6,문학 > 일본문학 > 소설,312,http://image.aladin.co.kr/product/15848/6/cove...,NaN,NaN,NaN,None
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196,03300,,334.0,"사회과학 > 사회학, 사회문제 > 사회문제",293,https://image.aladin.co.kr/product/19874/76/co...,244쪽,324g,140*210*16mm,"[2019년, 07월, 17일]"
9,10,9,쇼코의 미소 :최은영 소설,지은이: 최은영,문학동네,2016,9788954641630,03810,,813.7,문학 > 한국문학 > 소설,293,https://bookthumb-phinf.pstatic.net/cover/107/...,296쪽,406g,145*210*20mm,"[2016년, 07월, 04일]"

## `merge()` 함수의 매개변수

In [ ]:
df1 = pd.DataFrame({'col1': ['a','b','c'], 'col2': [1,2,3]})
df1

In [ ]:
df2 = pd.DataFrame({'col1': ['a','b','d'], 'col3': [10,20,30]})
df2

In [ ]:
pd.merge(df1, df2, on='col1')

In [ ]:
pd.merge(df1, df2, how='left', on='col1')

In [ ]:
pd.merge(df1, df2, how='right', on='col1')

In [ ]:
pd.merge(df1, df2, how='outer', on='col1')

In [ ]:
pd.merge(df1, df2, left_on='col1', right_on='col1')

In [ ]:
pd.merge(df1, df2, left_on='col2', right_index=True)