In [ ]:
# 02-2 스크래핑 사용하기

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.jupyter.org/github/rickiepark/hg-da/blob/main/02-2.ipynb"><img src="https://jupyter.org/assets/share.png" width="61" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/hg-da/blob/main/02-2.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## 검색 결과 페이지 가져오기

In [37]:
import gdown

gdown.download('https://bit.ly/3q9SZix', '20s_best_book.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: C:\Users\YW\Desktop\mot\hg-da-main\20s_best_book.json
100%|█████████████████████████████████████████████████████████████████████████████| 92.9k/92.9k [00:00<00:00, 1.21MB/s]

'20s_best_book.json'

In [40]:
import pandas as pd

books_df = pd.read_json('20s_best_book.json')
books_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...

In [41]:
import requests

isbn = 9788954672214     
url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'

r = requests.get(url.format(isbn))

In [42]:
print(r.text)

	<!DOCTYPE html >
	<html lang="ko">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
	<meta http-equiv="Accept-CH-Lifetime" content="86400" />
	<meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />

    <title> 9788954672214 - 예스24</title>

	<meta name="title" content="예스24" />
	<meta name="description" content="도서, 티켓, 음반, 굿즈, 커뮤니티까지 문화 전반을 아우르는 국내 대표 문화콘텐츠 플랫폼, 아낌없는 혜택과 총알배송을 경험해보세요." />
	<meta name="keywords" content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" />


	<link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/util.js?v=20251114_a"></script>
	<script type="text/javascript" charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20250618"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20250618"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250613"></script>
    <script type="text/javascript" src="https://image.yes24.com/static/common/bulletSearch.js?v=20260107"></script>
	<script type="text/javascript" src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20251201"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/frontCommon.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20250613"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20251111_1"></script>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20250818" charset="euc-kr"/>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20250818" />

	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260113" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20260422" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260205" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20250818" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20250818" />

	<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
	<![endif]-->

	<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />

	<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);
		// 브레이즈 위한 설정 값
		var TUSERNO = '';
		var isUnder14 = 'False';

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
	<script type="text/javascript" src="https://www.yes24.com/javascript/common.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250916"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260326"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260421"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260421" defer></script>
	<script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260421"></script>
	<script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260421"></script>


	<!-- 광고 스크립트 - 공통 -->
        <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
    <!-- End Google Tag Manager -->
	<script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>

<link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?v=20260323' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/search/search.css?v=220250818' type='text/css' media='all'></head>
<body>

	<!-- 광고 스크립트 - 공통 -->
     <!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
	<dt>콘텐츠 바로가기</dt>
	<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>

<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div id="yesWrap" class="">
	<div id="yesHeaderArea" style="">
	<!-- ########## TOPBANNER 영역 시작 ########## -->
	<section>
		<div id="upperBnWrap" style="display:none;">
			<div id="upperBnRoll">
				<div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#e9c1fb"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_L_04.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#d1f7cc"><a href="https://event.yes24.com/present?eventno=268401" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_R_04.png" width="480" height="50" alt="에코백책키링"></a></div>
	</div>
</div><div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#ffeeb3"><a href="https://event.yes24.com/template?EventNo=268440" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_L_06.png" width="480" height="50" alt="리딩런"></a></div>
		<div class="upperBnSetRgt" style="background-color:#d2ccf7"><a href="https://event.yes24.com/present?eventno=268401" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_R_06.png" width="480" height="50" alt="에코백책키링"></a></div>
	</div>
</div>
			</div>
			<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
		</div>
	</section>
	<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
	<!-- ########## TOPBANNER 영역 끝 ########## -->
	<!-- ########## HEADER 영역 시작 ########## -->
	<div id="yHeader">
		<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onClick="setWcode('001_004');"><svg role="img" aria-label="YES24" type="image/svg+xml"><image src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" width="200" height="103" alt="YES24"></image></svg></a></h1>
		<div id="yHeaderWrap">
			<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
			<div class="yHeaderTop">
				<h2 class="yBlind">YES24 카테고리 리스트</h2>
					<ul class="cateLi" id="ulCategoryList"><li class="cate001"><a title="국내도서" href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" ><em class="txt">국내도서</em></a></li><li class="cate002"><a title="외국도서" href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002"  onclick="setWcode('001_002_002')"  ><em class="txt">외국도서</em></a></li><li class="cate018"><a title="중고샵" href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" ><em class="txt">중고샵</em></a></li><li class="cate017"><a title="eBook" href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')"  ><em class="txt">eBook</em></a></li><li class="cateCrC"><a title="크레마클럽" href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')"  ><em class="txt">크레마클럽</em></a></li><li class="cate003"><a title="CD/LP" href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" ><em class="txt">CD/LP</em></a></li><li class="cate004"><a title="DVD/Blu-ray" href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" ><em class="txt">DVD/BD</em></a></li><li class="cate006"><a title="GIFT" href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" ><em class="txt"><u>문구</u>/GIFT</em></a></li><li class="cateENT"><a title="티켓" href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank"  ><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
				<h2 class="yBlind">YES24 유틸메뉴</h2>
				<ul class="utilLi">
					<li id="LoginText">
						<input type="hidden" id="hdfLoginYn" value="N" />

							<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>

					</li>

						<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>

					<li class="myPgGrp">
						<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
						<dl class="myPgDl">
							<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
							<dd>
								<ul>
									<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
									<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
									<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
								</ul>
							</dd>
						</dl>
					</li>
					<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')" ><em class="txt">카트</em></a></li>
					<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>
					<li class="lastLi"><a href="https://www.yes24.com/Templates/FTCusMain.aspx?Wcode=001_003_012" onclick="setWcode('001_003_012')"><em class="txt">고객센터</em></a></li>
				</ul>
				<dl class="globalYesInfoDl">
					<dt><a href="javascript:void(0);" ><em class="txt">Global YES24</em><em class="ico_arr bgGNB">안내보기</em></a></dt>
					<dd>
						<div class="globalYesInfoContArea">
							<div class="globalYesInfoCont">
								<p class="yesInfo_tit">Global YES24는?</p>
								<p class="yesInfo_des">
									K-POP/K-Drama 관련상품(음반,도서,DVD)을<br/> 영문/중문 으로 이용하실 수 있습니다.
								</p>
								<div class="yesInfo_globalTxt">
									<p class="globalTxt_des">
										Korean wave shopping mall, sell the <br/>K-POP/K-Drama (CD,DVD,Blu-ray,Book)
										We aceept PayPal/UnionPay/Alipay<br/> and support English/Chinese Language service
									</p>
									<a href="https://global.yes24.com" target="_blank" onclick="setWcode('001_016_002')" class="btnC btn_blue"><span class="bWrap"><em class="txt">English</em></span></a>
									<p class="globalTxt_des">
									 作&#x4E3A;出&#x552E;正&#x89C4; K-POP/K-Drama 相&#x5173;(CD,&#x56FE;&#x4E66;,DVD) &#x97E9;流商品的&#x7F51;站, 支持 中文/英文 等海外&#x7ED3;&#x8D26;方式
									</p>
									<a href="https://cn.yes24.com" target="_blank" onclick="setWcode('001_016_003')" class="btnC btn_blue"><span class="bWrap"><em class="txt">中文</em></span></a>
                                    <p class="globalTxt_des">
									 Exclusive ticket sales for domestic and international pop artists
									</p>
									<a href="http://ticket.yes24.com/English?Gcode=009_205" target="_blank" onclick="setWcode('001_016_004')" class="btnC btn_blue"><span class="bWrap"><em class="txt">Global yesticket</em></span></a>
								</div>
							</div>
						</div>
					</dd>
				</dl>
			</div>
		   <!-- %%%%%%%%%% 해더 Top 영역 끝 %%%%%%%%%% -->
			<hr/>
			<!-- %%%%%%%%%% 해더 Mid 영역 시작 %%%%%%%%%% -->
			<div class="yHeaderMid">
				<div class="yesSearch">
					<form id="yesSForm" method="get" name="HeadForm" action="//www.yes24.com/product/search?" onsubmit="return check_search();" accept-charset="utf-8">
					<input type="hidden" id="keywordAd" name="keywordAd" value=""/>
					<input type="hidden" id="keyword" name="keyword" />
					<input type="hidden" id="domain" name="domain" value="ALL" />
					<input type="hidden" id="qdomain" name="qdomain" value="전체" />

					<fieldset>
					<legend>검색</legend>
					<span class="schIpt">
						<label><input type="text" title="YES24 검색어 입력" class="iptTxt" accesskey="s" id="query" name="query"
										maxlength="80" value="" style="ime-mode: active;" autocomplete="off"
										onfocus="showLatestSearchList();" onblur="blurSearchBar();"
										onkeydown="SearchBarRenderingEnableSet(false);init_searchbox();"
										onmousedown="SearchBarRenderingEnableSet(false);Common_init_searchbox();" /></label>
					</span>
					<div style="position:absolute;top:-1000em;left:0;width:1px;height:1px;overflow:hidden;">


						<script type="text/javascript" src="//adgirl.yes24.com/RealMedia/ads/adstream_mjx.ads/www.yes24.com/Header/SearchBar@x01" charset='euc-kr'></script>
						<script type="text/javascript">
							try {
								OAS_RICH("x01");
							} catch (e) { }
						</script>

					</div>
					<script type="text/javascript">
						var url = location.href;
						var reUrl = url.toLowerCase();

						$(document).ready(function () {
							//검색결과
						    if (reUrl.indexOf('/product/search') > -1 && reUrl.indexOf('/product/search/searchkeyword') <= 0) {
								SearchBarRenderingEnable = false;

								if (getParamValue("query") != undefined) {
									$("#query").val($("#hidSearchWord").val());
									fnGetValueDomain($("#hidSearchDomain").val());
									$("#domain").val($("#hidSearchDomain").val());
									$("#qdomain").val($("#hidSearchQdomain").val());
								}
							}
							if (SearchBarRenderingEnable == true) {
								fnSearchBarRendering();
							}
						});

						// 검색어 입력창에 포커스 시
						function SearchBarRenderingEnableSet(enable) {
							//광고 제거
							SearchBarRenderingEnable = enable;
							$("#ulSchScopeOpt").hide();
						}

						// 검색어 입력창 광고 노출
						function fnSearchBarRendering() {
							var seardtext = $('#hdSearchBarText').val();
							var bannerLink = $("#hdSearchBarLink").val();

							$('#query').val(seardtext);
							$('#query').addClass("iptTxt iptTxtAd");
							$('#keywordAd').val(bannerLink);
						}

						//검색창 선택 시
						function showLatestSearchList() {
							SearchBarRenderingEnableSet(false);
							if (String($("input#query").val()).length == 0) {
								try{
									srchHistory.show();
								}catch(e){}
								$("#suggestSearchList").hide();
								$("#searchKeyLayer").show();
								$("#latestSearchList").show();
							} else {
								BulletSearchRenewal.InitBulletSearch();
								showSuggestSearchList();
							}
						}

						//검색창 포커스 아웃
						function blurSearchBar() {
							var queryValue = $("#query").val();
							if (queryValue == "" || queryValue == null) {
                                if (location.href.toLowerCase().indexOf('/product/search') == -1) {

## 뷰티플수프

In [43]:
from bs4 import BeautifulSoup

In [44]:
soup = BeautifulSoup(r.text, 'html.parser')

In [45]:
prd_link = soup.find('a', attrs={'class':'gd_name'})

In [46]:
print(prd_link)

<a class="gd_name" href="/product/goods/90367403" onclick="wiseLogV2('S', '101_005_003_001', ''); setGoodsClickExtraCodeHub('032', '9788954672214', '90367403', '0',this);">시선으로부터,</a>

In [47]:
print(prd_link['href'])

/product/goods/90367403

In [48]:
url = 'http://www.yes24.com'+prd_link['href']
r = requests.get(url)

In [49]:
print(r.text)

	<!DOCTYPE html >
	<html lang="ko">

<head><link rel="canonical" href="https://www.yes24.com/product/goods/90367403"> <link rel="alternate" media="only screen and (max-width: 640px)"  href="https://m.yes24.com/goods/detail/90367403">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
	<meta http-equiv="Accept-CH-Lifetime" content="86400" />
	<meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />

    <title>시선으로부터, | 정세랑 | 문학동네 - 예스24 </title>


<meta name="title" content="시선으로부터,"/>
<meta name="author" content="정세랑 저" />

<meta name="description" content="시선으로부터,. “이 소설은 무엇보다 20세기를 살아낸 여자들에게 바치는 21세기의 사랑이다.”한국문학이 당도한 올곧은 따스함, 정세랑 신작 장편소설독창적인 목소리와 세계관으로 구축한 SF소설부터 우리 시대의 현실에 단단히 발 딛고 나아가는 이야기들까지, 폭넓..."/>

<meta name="keywords" content="카리나가읽은책,ReadWithMe_스타추천도서,2020젊은작가TOP5,추리책방,세계여성의날,여성의날,KBS우리시대의소설,내맘대로올해의책,북클러버의선택,2021서울국제도서전,책읽아웃,뭐읽지,문학뉴스레터에소개된책,다시보는2020,올해의책,사랑의형태,가족소설,여자들의이야기,여성서사,정세랑 저, 문학동네,8954672213,9788954672214"/>

<!-- Facebook Interface -->
<meta property="og:title" content="시선으로부터, | 정세랑 | 문학동네 - 예스24" />
<meta property="og:type" content="book" />
<meta property="og:url" content="https://www.yes24.com/product/goods/90367403" />
<meta property="og:image" content="https://image.yes24.com/goods/90367403/xl" />
<meta property="og:site_name" content="예스24" />
<meta property="og:description" content="“이 소설은 무엇보다 20세기를 살아낸 여자들에게 바치는 21세기의 사랑이다.”한국문학이 당도한 올곧은 따스함, 정세랑 신작 장편소설독창적인 목소리와 세계관으로 구축한 SF소설부터 우리 시대의 현실에 단단히 발 딛고 나아가는 이야기들까지, 폭넓은 작품 세계로 ..." />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="https://www.yes24.com/product/goods/90367403" />
<meta name="twitter:title" content="시선으로부터, | 정세랑 | 문학동네 - 예스24" />
<meta name="twitter:description" content="“이 소설은 무엇보다 20세기를 살아낸 여자들에게 바치는 21세기의 사랑이다.”한국문학이 당도한 올곧은 따스함, 정세랑 신작 장편소설독창적인 목소리와 세계관으로 구축한 SF소설부터 우리 시대의 현실에 단단히 발 딛고 나아가는 이야기들까지, 폭넓은 작품 세계로 ..." />
<meta name="twitter:image" content="https://image.yes24.com/goods/90367403/xl" />

<meta property="books:isbn" content="9788954672214"/>
<meta property="books:rating:value" content="9.4"/>
<meta property="books:rating:scale" content="10"/>
<meta property="books:rating:normalized_value" content="0"/>



	<link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/util.js?v=20251114_a"></script>
	<script type="text/javascript" charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20250618"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20250618"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250613"></script>
    <script type="text/javascript" src="https://image.yes24.com/static/common/bulletSearch.js?v=20260107"></script>
	<script type="text/javascript" src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20251201"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/frontCommon.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20250613"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20251111_1"></script>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20250818" charset="euc-kr"/>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20250818" />

	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260113" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20260422" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260205" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20250818" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20250818" />

	<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
	<![endif]-->

	<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />

	<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);
		// 브레이즈 위한 설정 값
		var TUSERNO = '';
		var isUnder14 = 'False';

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
	<script type="text/javascript" src="https://www.yes24.com/javascript/common.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250916"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260326"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260421"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260421" defer></script>
	<script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260421"></script>
	<script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260421"></script>


	<!-- 광고 스크립트 - 공통 -->
        <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
    <!-- End Google Tag Manager -->
	<script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>

<link rel='stylesheet' href='https://image.yes24.com/sysimage/YESUI/detail/detail_2nd.css?ver=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/YESUI/detail/detail_class.css?ver=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/yesUI.css?ver=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/yesLocation.css?ver=20250818' type='text/css' media='all'>



    <!-- 구조화된 데이터 -->
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": ["Book","Product"],
            "name": "시선으로부터,",
            "image": "https://image.yes24.com/goods/90367403/xl",
            "description": "시선으로부터,, “이 소설은 무엇보다 20세기를 살아낸 여자들에게 바치는 21세기의 사랑이다.”한국문학이 당도한 올곧은 따스함, 정세랑 신작 장편소설독창적인 목소리와 세계관으로 구축한 SF소설부터 우리 시대의 현실에 단단히 발 딛고 나아가는 이야기들까지, 폭넓...",
            "genre": ["소설/시/희곡","한국소설","한국 장편소설"],
            "award": ["오늘의 젊은 예술가상"],
            "keywords": "시선으로부터, 카리나가읽은책, ReadWithMe_스타추천도서, 2020젊은작가TOP5, 추리책방, 세계여성의날, 여성의날, KBS우리시대의소설, 내맘대로올해의책, 북클러버의선택, 2021서울국제도서전, 책읽아웃, 뭐읽지, 문학뉴스레터에소개된책, 다시보는202...",
            "isbn": "9788954672214",
            "bookFormat": "https://schema.org/Paperback",
            "datePublished": "2020-06-05",
            "numberOfPages": 340,
                    "inLanguage": "ko-KR",
            "url": "https://www.yes24.com/product/goods/90367403",
        "aggregateRating": {
              "@type": "AggregateRating",
              "ratingValue": 9.4,
              "reviewCount": 1001,
              "bestRating": 10.0,
              "worstRating": 0.0
            },
            "author": {
                "@type": "Person",
                "name": "정세랑"
                ,"url": "https://www.yes24.com/product/author/165526"
            },
            "publisher": {
                "@type":"Organization",
                "name":"문학동네"
            },
            "imageObject": {
                "@type": "ImageObject",
                "contentUrl": "https://image.yes24.com/goods/90367403/xl",
                "name": "시선으로부터,",
                "description": "시선으로부터,, “이 소설은 무엇보다 20세기를 살아낸 여자들에게 바치는 21세기의 사랑이다.”한국문학이 당도한 올곧은 따스함, 정세랑 신작 장편소설독창적인 목소리와 세계관으로 구축한 SF소설부터 우리 시대의 현실에 단단히 발 딛고 나아가는 이야기들까지, 폭넓...",
                "creditText": "YES24 제공",
                    "creator": {
                        "@type": "Organization",
                        "name": "YES24"
                    },
                "copyrightNotice": "YES24 Inc."
            },
            "VideoObject": {
                "@context": "https://schema.org",
                "@type": "VideoObject",
                "name": "'내가 안목이 있구나' 명작을 먼저 알아본 김나영의 추천서 | 김나영 | 리드윗미",
                "description": "시선으로부터, 관련 채널예스 동영상",
                "thumbnailUrl": "https://img.youtube.com/vi/-CCDF8VOTDg/hqdefault.jpg",
                "uploadDate": "2025-01-10 00:00:00+09:00",
                "contentUrl": "https://www.youtube.com/embed/-CCDF8VOTDg?si=wCvucHTSEmNP96WE",
                "embedUrl": "https://ch.yes24.com/video/detail/60008"
            },
                    "offers": {
                "@type": "Offer",
                "price": 12600,
                "priceCurrency": "KRW",
                "availability": "https://schema.org/InStock",
                "url": "https://www.yes24.com/product/goods/90367403",
                "itemCondition": "https://schema.org/NewCondition"

            },
            "workExample": [{
                "@type": "Book",
                "name": "시선으로부터,",
                "bookFormat": "https://schema.org/EBook",
                "isbn": "9788954672634",
                "inLanguage": "ko-KR",
                "url": "https://www.yes24.com/product/goods/90980188"
                }]


        }
    </script>
</head>
<body>

	<!-- 광고 스크립트 - 공통 -->
     <!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
	<dt>콘텐츠 바로가기</dt>
	<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>

<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div id="yesWrap" class="">
	<div id="yesHeaderArea" style="">
	<!-- ########## TOPBANNER 영역 시작 ########## -->
	<section>
		<div id="upperBnWrap" style="display:none;">
			<div id="upperBnRoll">
				<div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#e9c1fb"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_L_04.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#d1f7cc"><a href="https://event.yes24.com/present?eventno=268401" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_R_04.png" width="480" height="50" alt="에코백책키링"></a></div>
	</div>
</div><div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#ffeeb3"><a href="https://event.yes24.com/template?EventNo=268440" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_L_06.png" width="480" height="50" alt="리딩런"></a></div>
		<div class="upperBnSetRgt" style="background-color:#d2ccf7"><a href="https://event.yes24.com/present?eventno=268401" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0413_topbn_480x50_R_06.png" width="480" height="50" alt="에코백책키링"></a></div>
	</div>
</div>
			</div>
			<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
		</div>
	</section>
	<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
	<!-- ########## TOPBANNER 영역 끝 ########## -->
	<!-- ########## HEADER 영역 시작 ########## -->
	<div id="yHeader">
		<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onClick="setWcode('001_004');"><svg role="img" aria-label="YES24" type="image/svg+xml"><image src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" width="200" height="103" alt="YES24"></image></svg></a></h1>
		<div id="yHeaderWrap">
			<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
			<div class="yHeaderTop">
				<h2 class="yBlind">YES24 카테고리 리스트</h2>
					<ul class="cateLi" id="ulCategoryList"><li class="cate001 cateOn"><a title="국내도서" href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" ><em class="txt">국내도서</em></a></li><li class="cate002"><a title="외국도서" href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002"  onclick="setWcode('001_002_002')"  ><em class="txt">외국도서</em></a></li><li class="cate018"><a title="중고샵" href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" ><em class="txt">중고샵</em></a></li><li class="cate017"><a title="eBook" href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')"  ><em class="txt">eBook</em></a></li><li class="cateCrC"><a title="크레마클럽" href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')"  ><em class="txt">크레마클럽</em></a></li><li class="cate003"><a title="CD/LP" href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" ><em class="txt">CD/LP</em></a></li><li class="cate004"><a title="DVD/Blu-ray" href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" ><em class="txt">DVD/BD</em></a></li><li class="cate006"><a title="GIFT" href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" ><em class="txt"><u>문구</u>/GIFT</em></a></li><li class="cateENT"><a title="티켓" href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank"  ><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
				<h2 class="yBlind">YES24 유틸메뉴</h2>
				<ul class="utilLi">
					<li id="LoginText">
						<input type="hidden" id="hdfLoginYn" value="N" />

							<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>

					</li>

						<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>

					<li class="myPgGrp">
						<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
						<dl class="myPgDl">
							<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
							<dd>
								<ul>
									<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
									<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
									<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
								</ul>
							</dd>
						</dl>
					</li>
					<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')" ><em class="txt">카트</em></a></li>
					<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>

In [50]:
soup = BeautifulSoup(r.text, 'html.parser')
prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
print(prd_detail)

<div class="gd_infoSet infoSet_noLine" id="infoset_specific">
<div class="tm_infoSet">
<h4 class="tit_txt">품목정보</h4>
</div>
<div class="infoSetCont_wrap">
<div class="yesTb">
<table class="tb_nor tb_vertical" summary="품목정보 국내도서, 외국도서 " width="100%">
<caption>품목정보</caption>
<colgroup>
<col width="170"/>
<col width="*"/>
</colgroup>
<tbody class="b_size">
<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2020년 06월 05일</td>
</tr>
<tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">340쪽 | 412g | 133*200*23mm</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9788954672214</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">8954672213</td>
</tr>
</tbody>
</table>
</div>
</div>
<script type="text/javascript">
        if ($("#infoset_specific table tbody tr").length == 0) {
            $("#infoset_specific").remove();
        }
    </script>
</div>

In [51]:
prd_tr_list = prd_detail.find_all('tr')
print(prd_tr_list)

[<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2020년 06월 05일</td>
</tr>, <tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">340쪽 | 412g | 133*200*23mm</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9788954672214</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">8954672213</td>
</tr>]

In [52]:
for tr in prd_tr_list:
    if tr.find('th').get_text() == '쪽수, 무게, 크기':
        page_td = tr.find('td').get_text()
        
    elif tr.find('th').get_text() == '발행일':
        page_td2 = tr.find('td').get_text()

In [53]:
print(page_td)
print(page_td2)

340쪽 | 412g | 133*200*23mm
2020년 06월 05일

In [54]:
print(page_td.split()[0])

340쪽

## 전체 도서의 쪽수 구하기

In [55]:
def get_page_cnt(isbn):
    # Yes24 도서 검색 페이지 URL
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
    # URL에 ISBN을 넣어 HTML 가져옵니다.
    r = requests.get(url.format(isbn))
    soup = BeautifulSoup(r.text, 'html.parser')   # HTML 파싱
    # 검색 결과에서 해당 도서를 선택합니다.
    prd_info = soup.find('a', attrs={'class':'gd_name'})
    if prd_info == None:
        return ''
    # 도서 상세 페이지를 가져옵니다.
    url = 'http://www.yes24.com'+prd_info['href']
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    # 상품 상세정보 div를 선택합니다.
    prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
    # 테이블에 있는 tr 태그를 가져옵니다.
    prd_tr_list = prd_detail.find_all('tr')
    # 쪽수가 들어 있는 th를 찾아 td에 담긴 값을 반환합니다.
    for tr in prd_tr_list:
        if tr.find('th').get_text() == '쪽수, 무게, 크기':
            page = tr.find('td').get_text().split()[0]
            weight = tr.find('td').get_text().split()[2]
            size = tr.find('td').get_text().split()[4]
        if tr.find('th').get_text() == '발행일':
            date = tr.find('td').get_text().split()
    return page,weight,size,date

In [70]:
get_page_cnt(9791190090018)

('344쪽', '496g', '130*198*30mm', ['2019년', '06월', '24일'])

In [59]:
top10_books = books_df.head(10)

In [63]:
def get_page_cnt2(row):
    isbn = row['isbn13']
    return get_page_cnt(isbn)

In [66]:
page_count = top10_books.apply(get_page_cnt2, axis=1)
print(page_count)

0    (344쪽, 496g, 130*198*30mm, [2019년, 06월, 24일])
1    (300쪽, 358g, 134*200*20mm, [2020년, 07월, 08일])
2    (228쪽, 296g, 130*195*15mm, [2019년, 07월, 31일])
3    (340쪽, 412g, 133*200*23mm, [2020년, 06월, 05일])
4    (264쪽, 388g, 134*195*20mm, [2017년, 03월, 31일])
5    (396쪽, 512g, 145*210*30mm, [2016년, 11월, 21일])
6    (272쪽, 318g, 137*197*18mm, [2020년, 01월, 06일])
7
8    (244쪽, 324g, 140*210*16mm, [2019년, 07월, 17일])
9    (296쪽, 406g, 145*210*20mm, [2016년, 07월, 04일])
dtype: object

In [62]:
page_count = top10_books.apply(lambda row: get_page_cnt(row['isbn13']), axis=1)

In [80]:
page_count.name = 'page_count'
print(page_count[0][0])

344쪽

In [85]:
results = []
for isbn in top10_books['isbn13']:
    results.append(get_page_cnt(isbn))
    
page_count = pd.DataFrame(results, 
                          columns=['쪽수', '무게', '크기', '발행일'], 
                          index=top10_books.index)

In [86]:
top10_with_page_count = pd.merge(top10_books, page_count,
                                 left_index=True, right_index=True)
top10_with_page_count

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL,쪽수,무게,크기,발행일
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...,344쪽,496g,130*198*30mm,"[2019년, 06월, 24일]"
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...,300쪽,358g,134*200*20mm,"[2020년, 07월, 08일]"
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...,228쪽,296g,130*195*15mm,"[2019년, 07월, 31일]"
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...,340쪽,412g,133*200*23mm,"[2020년, 06월, 05일]"
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...,264쪽,388g,134*195*20mm,"[2017년, 03월, 31일]"
5,6,6,피프티 피플 :정세랑 장편소설,지은이: 정세랑,창비,2016,9788936434243,03810,,813.7,문학 > 한국문학 > 소설,320,https://bookthumb-phinf.pstatic.net/cover/113/...,396쪽,512g,145*210*30mm,"[2016년, 11월, 21일]"
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005,03810,,813.7,문학 > 한국문학 > 소설,319,https://image.aladin.co.kr/product/22246/11/co...,272쪽,318g,137*197*18mm,"[2020년, 01월, 06일]"
7,8,8,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9788972756194,03830,,833.6,문학 > 일본문학 > 소설,312,http://image.aladin.co.kr/product/15848/6/cove...,NaN,NaN,NaN,None
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196,03300,,334.0,"사회과학 > 사회학, 사회문제 > 사회문제",293,https://image.aladin.co.kr/product/19874/76/co...,244쪽,324g,140*210*16mm,"[2019년, 07월, 17일]"
9,10,9,쇼코의 미소 :최은영 소설,지은이: 최은영,문학동네,2016,9788954641630,03810,,813.7,문학 > 한국문학 > 소설,293,https://bookthumb-phinf.pstatic.net/cover/107/...,296쪽,406g,145*210*20mm,"[2016년, 07월, 04일]"

## `merge()` 함수의 매개변수

In [ ]:
df1 = pd.DataFrame({'col1': ['a','b','c'], 'col2': [1,2,3]})
df1

In [ ]:
df2 = pd.DataFrame({'col1': ['a','b','d'], 'col3': [10,20,30]})
df2

In [ ]:
pd.merge(df1, df2, on='col1')

In [ ]:
pd.merge(df1, df2, how='left', on='col1')

In [ ]:
pd.merge(df1, df2, how='right', on='col1')

In [ ]:
pd.merge(df1, df2, how='outer', on='col1')

In [ ]:
pd.merge(df1, df2, left_on='col1', right_on='col1')

In [ ]:
pd.merge(df1, df2, left_on='col2', right_index=True)